name: CD

on:
  push:
    branches:
      - main

jobs:

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t niwatoko .
        
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push Docker image
      run: |
        docker tag niwatoko ${{ secrets.DOCKERHUB_USERNAME }}/niwatoko:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/niwatoko:latest

  deploy:
    needs: build-and-push-docker-image
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      # ここでは、実際のデプロイ手順を記述します。
      # 例えば、SSHを使ってサーバーに接続し、docker-composeを使ってデプロイするなど。
      run: |
        # デプロイコマンドを記述
